config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'

  resources :posts

  match 'users/sign_in', via: %i(post get), as: :sign_in
  match 'users/sign_up', via: %i(post get), as: :sign_up
  get   'users/sign_out', as: :sign_out
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user

  scope :longer_than, lambda { |length| where("length('body') > #{length}") }

  validates :title, :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  validates_uniqueness_of :username
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include ApplicationHelper

  def authenticate_user!
    redirect_to sign_in_path, notice: 'You need to be signed in first' unless user_signed_in?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i(index show)

  def index
    @posts = Post.all.order(id: :desc)
    @posts.where!("body LIKE '%#{params[:query]}%'") if params[:query]
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def update
    @post = current_user.posts.find(params[:id])

    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])

    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private

  def post_params
    params.require(:post).permit(:user_id, :title, :body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token

  def sign_in
    if request.post?
      user = User.find_by(params[:user])
      if user.present?
        session[:user_id] = user.id
        redirect_to root_path, notice: 'You are now logged in'
      else
        flash.now[:notice] = 'Username or password are invalid'
      end
    end
  end

  def sign_up
    if request.post?
      @user = User.new user_params
      if @user.save
        session[:user_id] = @user.id
        redirect_to root_path, notice: 'Your account has been created'
      else
        flash.now[:notice] = @user.errors.full_messages.join(' ')
      end
    else
      @user = User.new
    end
  end

  def sign_out
    session[:user_id] = nil
    redirect_to root_path, notice: 'You have been signed out'
  end

  protected
  def user_params
    params[:user].permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def user_signed_in?
    !!current_user
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_flash_message.html.haml
- if notice.present?
  .alert.alert-info.fade.in
    %button.close{ 'data-dismiss' => 'alert' } ×
    = notice

app/views/layouts/_navigation.haml
%nav.navbar.navbar-default{ role: 'navigation' }
  .navbar-header
    %button.navbar-toggle{ 'data-target' => '.main-navigation', 'data-toggle' => 'collapse', type: 'button' }
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand{ href: root_path } Posts
  .collapse.navbar-collapse.main-navigation
    %ul.nav.navbar-nav.navbar-right
      - if user_signed_in?
        %li
          = link_to 'Sign Out', sign_out_path
      - else
        %li
          = link_to 'Sign In', sign_in_path
        %li
          = link_to 'Sign Up', sign_up_path

app/views/layouts/application.haml
!!!
%html
  %head
    %title Recruitment
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render partial: 'layouts/navigation'

    .container
      = render partial: 'layouts/flash_message'
      = yield

app/views/posts/_form.html.haml
= simple_form_for(@post) do |f|
  = f.input :title
  = f.input :body, hint: 'Use <b></b> tags for bold text and <i></i> tags for italics'

  = f.button :submit, class: 'btn btn-primary'

app/views/posts/_post.html.haml
.post.panel.panel-default
  .panel-heading
    = post.title
  .panel-body
    = post.body.html_safe
    - unless current_page?(post)
      .text-right
        = link_to 'Show more...', post

app/views/posts/edit.html.haml
%h5 Edit Post
%hr

= render 'form'

app/views/posts/index.html.haml
.row
  %form{ action: posts_path, method: :get }
    .col-lg-6.col-lg-offset-2.col-xs-10
      .form-group
        = text_field_tag :query, params[:query], class: 'form-control'
    .col-lg-2.col-xs-2
      %input.btn.btn-default.pull-right{ type: 'submit', value: 'Search' }

.row
  .col-lg-8.col-lg-offset-2
    = render @posts

- if user_signed_in?
  .text-center
    = link_to 'Add Post', new_post_path, class: 'btn btn-primary'

app/views/posts/new.html.haml
%h5 New Post
%hr

= render 'form'

app/views/posts/show.html.haml
.row
  .col-lg-8.col-lg-offset-2
    = render @post

    - if @post.user == current_user
      = link_to 'Edit', edit_post_path(@post)
      |
      = link_to 'Delete', post_path(@post), method: :delete
      |
    = link_to 'Back', posts_path

app/views/users/sign_in.html.haml
.row
  .col-lg-8.col-lg-offset-2
    .panel.panel-default
      .panel-heading Sign in
      .panel-body
        = simple_form_for :user, url: sign_in_path, method: :post do |f|
          = f.input :username
          = f.input :password
          = f.submit 'Sign in', class: 'btn btn-primary'

app/views/users/sign_up.html.haml
.row
  .col-lg-8.col-lg-offset-2
    .panel.panel-default
      .panel-heading Sign up
      .panel-body
        = simple_form_for @user, url: sign_up_path, method: :post do |f|
          = f.input :username
          = f.input :password
          = f.submit 'Sign up', class: 'btn btn-primary'